
"use client";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { db } from "@/lib/firebase";
import { useToast } from "@/hooks/use-toast";
import { doc, setDoc, collection, writeBatch } from "firebase/firestore";
import { useState } from "react";
import { Loader2 } from "lucide-react";

// Dummy data to be seeded for the main dashboard stats
const dashboardStatsData = {
    totalConversations: { value: 1234, change: 15.2 },
    activeUsers: { value: 231, change: 21 },
    avgResponseTime: { value: '3.2s', change: -5 },
    satisfactionScore: { value: '92%', change: 2.1 },
    barChartData: [
      { month: "January", conversations: 186 },
      { month: "February", conversations: 305 },
      { month: "March", conversations: 237 },
      { month: "April", conversations: 273 },
      { month: "May", conversations: 209 },
      { month: "June", conversations: 214 },
    ],
    areaChartData: [
      { date: "2024-01-01", score: 88 },
      { date: "2024-02-01", score: 89 },
      { date: "2024-03-01", score: 91 },
      { date: "2024-04-01", score: 90 },
      { date: "2024-05-01", score: 92 },
      { date: "2024-06-01", score: 93 },
    ]
};


export default function SeedDatabasePage() {
    const [isLoading, setIsLoading] = useState(false);
    const { toast } = useToast();

    const handleSeed = async () => {
        setIsLoading(true);
        toast({ title: "Seeding Database...", description: "Please wait while we add the sample data." });
        
        try {
            const batch = writeBatch(db);

            // 1. Seed dashboard_stats
            const statsDocRef = doc(db, "dashboard", "stats");
            batch.set(statsDocRef, dashboardStatsData);

            // Note: We are no longer seeding chat data as it's now user-specific.
            // You can generate chats by sending messages to your WhatsApp number.

            await batch.commit();

            toast({
                title: "Database Seeded Successfully!",
                description: "Your dashboard is now populated with sample data.",
            });
        } catch (error: any) {
            console.error("Error seeding database: ", error);
            toast({
                variant: "destructive",
                title: "Error Seeding Database",
                description: error.message || "An unexpected error occurred.",
            });
        } finally {
            setIsLoading(false);
        }
    };


    return (
        <div className="flex justify-center items-center h-full">
            <Card className="w-full max-w-md">
                <CardHeader>
                    <CardTitle className="font-headline">Seed Your Database</CardTitle>
                    <CardDescription>
                        Click the button below to populate your Firestore database with sample dashboard data. Chat conversations are now generated by sending messages to your connected WhatsApp number.
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <Button onClick={handleSeed} disabled={isLoading} className="w-full">
                        {isLoading ? (
                            <>
                                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                Seeding...
                            </>
                        ) : (
                            "Seed Dashboard Data"
                        )}
                    </Button>
                </CardContent>
            </Card>
        </div>
    );
}
